"""Report generation domain logic."""

from __future__ import annotations

from collections import defaultdict
from datetime import date

from penny.transactions import TransactionFilter, list_transactions


def _category_at_depth(category: str, depth: str) -> str:
    """Return category truncated to specified depth."""
    cat = category or "uncategorized"
    if depth == "*":
        return cat
    depth_int = int(depth)
    parts = cat.split("/")
    return "/".join(parts[:depth_int])


def format_currency(cents: int) -> str:
    """Format cents as EUR using German separators."""
    amount = abs(cents) / 100
    formatted = f"{amount:,.2f}".replace(",", "_").replace(".", ",").replace("_", ".")
    sign = "-" if cents < 0 else ""
    return f"{sign}{formatted} EUR"


def category_bucket(category: str | None) -> str:
    """Group categories at the first visible level."""
    return (category or "uncategorized").split("/")[0]


def _period_label(from_date: date | None, to_date: date | None) -> str:
    return f"{from_date.isoformat() if from_date else 'beginning'} to {to_date.isoformat() if to_date else 'today'}"


def _account_label(account_ids: frozenset[int] | None) -> str:
    if not account_ids:
        return "all"
    return ", ".join(str(account_id) for account_id in sorted(account_ids))


def generate_report_text(filters: TransactionFilter | None = None, neutralize: bool = True) -> str:
    """Generate the plain-text financial report used by API and CLI."""
    transactions = list_transactions(filters=filters, limit=None, neutralize=neutralize)

    expense_total = sum(
        abs(transaction.amount_cents)
        for transaction in transactions
        if transaction.amount_cents < 0
    )
    income_total = sum(
        transaction.amount_cents for transaction in transactions if transaction.amount_cents > 0
    )
    net_flow = income_total - expense_total

    expense_categories: dict[str, int] = defaultdict(int)
    income_categories: dict[str, int] = defaultdict(int)
    for transaction in transactions:
        bucket = category_bucket(transaction.category)
        if transaction.amount_cents < 0:
            expense_categories[bucket] += abs(transaction.amount_cents)
        elif transaction.amount_cents > 0:
            income_categories[bucket] += transaction.amount_cents

    top_expenses = sorted(expense_categories.items(), key=lambda item: item[1], reverse=True)[:10]
    top_income = sorted(income_categories.items(), key=lambda item: item[1], reverse=True)[:10]
    filters = filters or TransactionFilter()

    lines = [
        "=" * 79,
        "                              PENNY FINANCE REPORT",
        "=" * 79,
        "",
        f"Period:   {_period_label(filters.from_date, filters.to_date)}",
        f"Accounts: {_account_label(filters.account_ids)}",
        "",
        "SUMMARY",
        "-" * 7,
        f"  Transactions:    {len(transactions)}",
        f"  Total Income:    {format_currency(income_total)}",
        f"  Total Expenses:  {format_currency(expense_total)}",
        f"  Net Flow:        {format_currency(net_flow)}",
    ]

    if top_expenses:
        lines.extend(["", "TOP 10 EXPENSE CATEGORIES", "-" * 25])
        for index, (name, value) in enumerate(top_expenses, start=1):
            share = round((value / expense_total) * 100) if expense_total else 0
            lines.append(f"  {index}. {name:<20} {format_currency(value):>12}  ({share:>2}%)")

    if top_income:
        lines.extend(["", "TOP 10 INCOME CATEGORIES", "-" * 24])
        for index, (name, value) in enumerate(top_income, start=1):
            share = round((value / income_total) * 100) if income_total else 0
            lines.append(f"  {index}. {name:<20} {format_currency(value):>12}  ({share:>2}%)")

    lines.extend(["", "Report generated by Penny v0.2.0"])
    return "\n".join(lines)


def _format_pivot_section(
    title: str,
    period_totals: dict,
    ordered_periods: list[str],
    labels: list[str],
) -> str:
    """Render a single fixed-width pivot table section."""
    ordered_cats = sorted(period_totals.keys())

    cat_width = max(len("Category"), max((len(c) for c in ordered_cats), default=0))
    col_width = max(8, max((len(lbl) for lbl in labels), default=0))
    total_col = max(8, len("Total"))

    def fmt(cents: int) -> str:
        return f"{cents / 100:,.0f}".replace(",", "_").replace(".", ",").replace("_", ".")

    header = f"{'Category':<{cat_width}}"
    for lbl in labels:
        header += f"  {lbl:>{col_width}}"
    header += f"  {'Total':>{total_col}}"
    sep = "-" * len(header)

    data_lines = []
    col_sums = [0] * len(ordered_periods)
    grand_total = 0
    for cat in ordered_cats:
        row_total = sum(period_totals[cat].get(k, 0) for k in ordered_periods)
        grand_total += row_total
        line = f"{cat:<{cat_width}}"
        for i, k in enumerate(ordered_periods):
            v = period_totals[cat].get(k, 0)
            col_sums[i] += v
            cell = fmt(v) if v else "-"
            line += f"  {cell:>{col_width}}"
        line += f"  {fmt(row_total):>{total_col}}"
        data_lines.append(line)

    totals_line = f"{'TOTAL':<{cat_width}}"
    for s in col_sums:
        totals_line += f"  {fmt(s):>{col_width}}"
    totals_line += f"  {fmt(grand_total):>{total_col}}"

    return "\n".join(
        [
            "",
            title,
            "-" * len(header),
            header,
            sep,
            *data_lines,
            sep,
            totals_line,
        ]
    )


def generate_pivot_text(
    filters: TransactionFilter | None = None,
    granularity: str = "month",
    depth: str = "1",
    show_expenses: bool = True,
    show_income: bool = False,
    neutralize: bool = True,
) -> str:
    """Generate fixed-width pivot table section(s): categories × time periods."""
    from penny.api.helpers import period_key, period_label, sort_period_keys
    from penny.db import connect
    from penny.sql import breakout_query

    if not show_expenses and not show_income:
        return ""

    filters = filters or TransactionFilter()

    accounts_str: str | None = None
    if filters.account_ids:
        accounts_str = ",".join(str(a) for a in sorted(filters.account_ids))

    conn = connect()
    cursor = conn.cursor()
    sql, params = breakout_query(
        from_date=filters.from_date.isoformat() if filters.from_date else None,
        to_date=filters.to_date.isoformat() if filters.to_date else None,
        accounts=accounts_str,
        category=filters.category_prefix,
        q=filters.search_query,
        neutralize=neutralize,
    )
    rows = cursor.execute(sql, params).fetchall()
    conn.close()

    expense_totals: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    income_totals: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    periods: set[str] = set()

    for row in rows:
        amount = row[2]
        key = period_key(row[0], granularity)
        bucket = _category_at_depth(row[1], depth)
        periods.add(key)
        if amount < 0 and show_expenses:
            expense_totals[bucket][key] += abs(amount)
        elif amount > 0 and show_income:
            income_totals[bucket][key] += amount

    if not periods:
        return ""

    ordered_periods = sort_period_keys(list(periods), granularity)
    labels = [period_label(k, granularity) for k in ordered_periods]
    gran_label = f"depth: {depth}, granularity: {granularity}"

    sections = []
    if show_expenses and expense_totals:
        sections.append(
            _format_pivot_section(
                f"EXPENSE PIVOT  ({gran_label})", expense_totals, ordered_periods, labels
            )
        )
    if show_income and income_totals:
        sections.append(
            _format_pivot_section(
                f"INCOME PIVOT  ({gran_label})", income_totals, ordered_periods, labels
            )
        )
    return "\n".join(sections)
