"""Report generation domain logic."""

from __future__ import annotations

from collections import defaultdict
from datetime import date

from penny.transactions import TransactionFilter, list_transactions


def format_currency(cents: int) -> str:
    """Format cents as EUR using German separators."""
    amount = abs(cents) / 100
    formatted = f"{amount:,.2f}".replace(",", "_").replace(".", ",").replace("_", ".")
    sign = "-" if cents < 0 else ""
    return f"{sign}{formatted} EUR"


def category_bucket(category: str | None) -> str:
    """Group categories at the first visible level."""
    return (category or "uncategorized").split("/")[0]


def _period_label(from_date: date | None, to_date: date | None) -> str:
    return f"{from_date.isoformat() if from_date else 'beginning'} to {to_date.isoformat() if to_date else 'today'}"


def _account_label(account_ids: frozenset[int] | None) -> str:
    if not account_ids:
        return "all"
    return ", ".join(str(account_id) for account_id in sorted(account_ids))


def generate_report_text(filters: TransactionFilter | None = None) -> str:
    """Generate the plain-text financial report used by API and CLI."""
    transactions = list_transactions(filters=filters, limit=None, neutralize=False)

    expense_total = sum(abs(transaction.amount_cents) for transaction in transactions if transaction.amount_cents < 0)
    income_total = sum(transaction.amount_cents for transaction in transactions if transaction.amount_cents > 0)
    net_flow = income_total - expense_total

    expense_categories: dict[str, int] = defaultdict(int)
    income_categories: dict[str, int] = defaultdict(int)
    for transaction in transactions:
        bucket = category_bucket(transaction.category)
        if transaction.amount_cents < 0:
            expense_categories[bucket] += abs(transaction.amount_cents)
        elif transaction.amount_cents > 0:
            income_categories[bucket] += transaction.amount_cents

    top_expenses = sorted(expense_categories.items(), key=lambda item: item[1], reverse=True)[:5]
    top_income = sorted(income_categories.items(), key=lambda item: item[1], reverse=True)[:5]
    filters = filters or TransactionFilter()

    lines = [
        "=" * 79,
        "                              PENNY FINANCE REPORT",
        "=" * 79,
        "",
        f"Period:   {_period_label(filters.from_date, filters.to_date)}",
        f"Accounts: {_account_label(filters.account_ids)}",
        "",
        "SUMMARY",
        "-" * 7,
        f"  Transactions:    {len(transactions)}",
        f"  Total Income:    {format_currency(income_total)}",
        f"  Total Expenses:  {format_currency(expense_total)}",
        f"  Net Flow:        {format_currency(net_flow)}",
    ]

    if top_expenses:
        lines.extend(["", "TOP EXPENSE CATEGORIES", "-" * 22])
        for index, (name, value) in enumerate(top_expenses, start=1):
            share = round((value / expense_total) * 100) if expense_total else 0
            lines.append(f"  {index}. {name:<20} {format_currency(value):>12}  ({share:>2}%)")

    if top_income:
        lines.extend(["", "TOP INCOME CATEGORIES", "-" * 21])
        for index, (name, value) in enumerate(top_income, start=1):
            share = round((value / income_total) * 100) if income_total else 0
            lines.append(f"  {index}. {name:<20} {format_currency(value):>12}  ({share:>2}%)")

    lines.extend(["", "Report generated by Penny v0.1.0"])
    return "\n".join(lines)
