repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
      - id: test-no-ui
        name: test-no-ui
        entry: make test-no-ui
        language: system
        pass_filenames: false
